### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by sansko** [coolight7/MimicryMusic#1]
可以改下状态栏图标吗，显示的是flutter的图标

**Comment by coolight7** [comment]
ok，系统是安卓12以上吧，这个问题之前一直没注意到，近期会试试改掉

**Comment by sansko** [comment]
我是安卓9

**Comment by coolight7** [comment]
> 我是安卓9

这样啊，手上没有相关设备，我试试改改看。

**Comment by coolight7** [comment]
0.6.0 更新尝试改了这个，你更新看看好了没：
https://download.music.mimicry.cool/
