### ISSUE TITLE
[问题 - Android平台] 上划返回桌面手势导致程序行为异常

### ISSUE THREAD

**Issue by Xionghaizi001** [coolight7/MimicryMusic#101]
## 问题描述
上划返回桌面手势会使程序刷新当前页面或返回到上一级。
出现此问题时可能会出现以下两种情况：
- 如有输入控件，清空输入内容
- 如在“正在播放”等页面，会刷新当前页面状态。
此时无法与页面交互，只能再进行一次 “返回” 操作才可正常使用程序。

## 能否复现
极易复现(90%)。

## 复现步骤
1. 打开软件；
2. 找到任意需要输入的场景；
3. 使用“返回桌面”上划手势(此时如未松手则可观察到程序状态)；
4. 回到软件；
5. 打开“正在播放”页面；
6. 重复第三步；
7. 问题复现。

## 期望效果
返回桌面手势不影响程序运行

## 环境信息
设备：Meizu 20 PRO
系统：Flyme 11.2.0.0A @ Android 14
软件：V0.58.0 Main/小笼包

**Comment by coolight7** [comment]
- 唔我这边 hyperos 没有出现这个问题，没有设备复现问题可能不好修了
