### ISSUE TITLE
歌曲封面页，建议上滑切换下一曲，下滑切换上一曲

### ISSUE THREAD

**Issue by luo-chuan** [coolight7/MimicryMusic#16]
建议在歌曲封面页面，上滑下滑对应切换下一曲和上一曲，方便驾驶状态下切歌。

**Comment by luo-chuan** [comment]
作者说希望保留下滑返回。是这样的，我都不知道可以下滑返回，我是在尝试下滑能不能切歌的时候才发现下滑是返回。安卓用习惯了，一直都是屏幕边缘侧滑返回，已经形成肌肉记忆了，当我想返回的时候条件反射就是侧滑。可以做成一个选项吧，愿意下滑返回的就设置为下滑返回，愿意下滑切歌的就设置为下滑切歌。
有群友说可以用方向盘切歌。是这样的，我这边测试连接hicar，方向盘就切不动。另外呢，还有广大的老旧车、低端车的方向盘没有方控，开面包车的人也大有人在，他们的车甚至都没蓝牙，要用fm转蓝牙。

**Comment by coolight7** [comment]
> 作者说希望保留下滑返回。是这样的，我都不知道可以下滑返回，我是在尝试下滑能不能切歌的时候才发现下滑是返回。

* 内测目前有横屏时左右滑动切歌了噢，主要就是设置项不想搞太多

**Comment by luo-chuan** [comment]
怎么说呢，这并不是一个舒适性选项，而是一个安全性选项。对于没有条件用方向盘切歌及没有安卓中控屏的用户来说，他们只能利用手机屏幕切歌（一般来说手机是以竖屏形式夹在支架上的），如果要去点切歌键，必然会分散注意力，眼睛要盯着屏幕，不能做到盲操作，很危险。而上下滑动切歌就不一样了，可以盲操作，眼睛不用盯着屏幕，驾驶更安全。

**Comment by coolight7** [comment]
* 正式版更新已支持该功能，更新后启用设置-界面-歌曲图上下滑切歌即可

**Comment by luo-chuan** [comment]
![Screenshot_20231130_132520](https://github.com/coolight7/MimicryMusic/assets/33930736/51218265-20b6-4ac7-9287-216baacb379f)

![Screenshot_20231130_132334](https://github.com/coolight7/MimicryMusic/assets/33930736/61fa67fb-cc8b-4a4a-ac8a-ab8dab36c03c)

安卓完整版0.9.1竖屏时仍然是上滑上一句，下滑下一曲，麻烦再测试一下呢？

**Comment by coolight7** [comment]
好的下版本修
