### ISSUE TITLE
建议：有没有考虑多支持一些网盘，比如OneDrive之类的

### ISSUE THREAD

**Issue by TheTwoRites** [coolight7/MimicryMusic#17]
我现在是通过koofr连接OneDrive，让它能通过webdav链接访问，不过感觉很怪。

alist和rclone我懒得部署，也没有自己的服务器。

（win端的交互逻辑是不是根据手机端改的，操作起来好怪啊）

**Comment by coolight7** [comment]
* 外部云盘的接入在计划中，但比较久，而且很可能会考虑独立做一个新app专门做这个功能。
* win不是改的，是他们就是同一套代码，所以操作是一样的，不过现在也不想改，以后有空再看，目前两边就一直保持一致
