### ISSUE TITLE
可以单独记住每一个歌单的进度吗？

### ISSUE THREAD

**Issue by luo-chuan** [coolight7/MimicryMusic#19]
有时候想听不同的有声书，结果只能记住当前歌单的进度，很不方便。
现有功能不是我想要的效果。我想的是点播放列表最上面的播放键直接从上次的位置开始播放，但现在的效果还是从第一首歌曲开始。如果我想从第一首歌曲开始，我会直接点击第一首歌曲。
![Screenshot_20231027_190112](https://github.com/coolight7/MimicryMusic/assets/33930736/097c50ad-be83-45e0-83f4-3b3ef4679c52)
![Screenshot_20231027_190201](https://github.com/coolight7/MimicryMusic/assets/33930736/cab6a77a-e91e-4239-b8f0-0c5f7b6d37b0)

**Comment by coolight7** [comment]
* 可以做但由于之前的设计，这个不好改，所以不一定能很快就做出来。

**Comment by coolight7** [comment]
* 正式版更新已支持该功能
