### ISSUE TITLE
文件后缀mp3大写后无法识别

### ISSUE THREAD

**Issue by TheRainight** [coolight7/MimicryMusic#3]
![IMG_20230814_201132.jpg](https://github.com/coolight7/MimicryMusic/assets/33674307/d8d7eacb-4c38-429b-8abf-c25109d16668)

望修复

**Comment by coolight7** [comment]
好的收到！




coolight
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coolight7/MimicryMusic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 晚上8:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[coolight7/MimicryMusic] 文件后缀mp3大写后无法识别 (Issue #3)





 

 
望修复

**Comment by coolight7** [comment]
* 已修复，请更新最新的 0.6.71：
https://download.music.mimicry.cool/
