### ISSUE TITLE
UTF-16编码的歌曲信息乱码

### ISSUE THREAD

**Issue by qwqcwcawa** [coolight7/MimicryMusic#36]
![2024-04-03-22-02-05-246](https://github.com/coolight7/MimicryMusic/assets/156668576/f5449cb0-5281-438b-9e3e-f3592bf67ac4)
内嵌的歌词也显示不出来

**Comment by coolight7** [comment]
编码问题有做一些处理，但更多是针对外置歌词文件和webdav文件信息的。乱码这个其实也不好判断是哪个编码，所以还是建议自己用音乐标签编辑器之类的工具重新写入歌曲信息比较好
