### ISSUE TITLE
独立控制每个歌曲的音量

### ISSUE THREAD

**Issue by luo-chuan** [coolight7/MimicryMusic#4]
希望有这一功能。个别B站视频的声音很小或很大，希望能独立控制每个歌曲的音量，并记住该设置。比如对于声音特别小的歌曲，就把音量设置为+5%，+10%等等；对于声音特别大的歌曲，就把音量设置为-5%，-10%等等。这样就只需要设置一次，避免了每次听到该歌曲都要调整两次音量。

**Comment by coolight7** [comment]
* 是的我们也发现了这个问题，所以计划在后面会做一个，可以针对每一首歌指定执行一些功能，其中就包含音量调节。

**Comment by luo-chuan** [comment]
> * 是的我们也发现了这个问题，所以计划在后面会做一个，可以针对每一首歌指定执行一些功能，其中就包含音量调节。

想再提个需求，就是跳过片头和片尾，也是针对独立的歌曲设置的。因为有的视频会包含一个与音乐无关的片头和片尾，有点影响听音乐的沉浸感。

**Comment by coolight7** [comment]
* ok，不过这个计划整体是比较大的功能，排期得过一两个月之后。

**Comment by coolight7** [comment]
* 正式版已支持 自动任务
