### ISSUE TITLE
添加webdav音乐时，如果数量大几千首的话，会提示添加失败

### ISSUE THREAD

**Issue by jpw168** [coolight7/MimicryMusic#48]
扫描的歌曲数量是正确的，但是点击需要加到的歌单时，提示"复制中"，然后一会就提示失败。
下次重新进软件，该歌单歌曲显示为空。个人感觉是歌单列表文件太大，导致同步至服务器失败了
![微信图片_20240603132611](https://github.com/coolight7/MimicryMusic/assets/19659232/1901f232-87f2-4dc7-9d05-29543d771d16)
![微信图片_20240603132618](https://github.com/coolight7/MimicryMusic/assets/19659232/21acbd55-a079-46fa-8825-3f89ece3280f)
![微信图片_20240603132622](https://github.com/coolight7/MimicryMusic/assets/19659232/66d1c992-5a25-4ed5-9bb9-b3c5cec2f2dd)
![微信图片_20240603132847](https://github.com/coolight7/MimicryMusic/assets/19659232/75d9e86c-8d39-40fc-9979-7ff7f5b4f26d)

**Comment by coolight7** [comment]
是的，服务器有限制单个歌单数据应小于10MB，换算下来大约就是一个歌单内应当小于1w首歌左右

**Comment by coolight7** [comment]
可以使用本地歌单，它不限制歌曲数量

**Comment by jpw168** [comment]
> 是的，服务器有限制单个歌单数据应小于10MB，换算下来大约就是一个歌单内应当小于1w首歌左右

是否有计划把大歌单数据副本保存至本地？主要是下次打开app会丢失，还需要手动再次添加。
这种大歌单数据一般不需要考虑跨平台同步的，减少服务器压力

**Comment by coolight7** [comment]
> 是否有计划把大歌单数据副本保存至本地？主要是下次打开app会丢失，还需要手动再次添加。 这种大歌单数据一般不需要考虑跨平台同步的，减少服务器压力

直接用本地歌单就可以了，不会同步不需要网络加载也不限制歌曲数量

**Comment by jpw168** [comment]
> > 是否有计划把大歌单数据副本保存至本地？主要是下次打开app会丢失，还需要手动再次添加。 这种大歌单数据一般不需要考虑跨平台同步的，减少服务器压力
> 
> 直接用本地歌单就可以了，不会同步不需要网络加载也不限制歌曲数量
汗，我一直以为本地歌单只能导入本地歌曲
谢了。
