### ISSUE TITLE
歌单封面通过BV号提取

### ISSUE THREAD

**Issue by luo-chuan** [coolight7/MimicryMusic#5]
建议歌单的封面可以通过BV或者AV号提取来设置。因为用户有时候会一个歌单对应一个Bili视频合集。这样也可以避免用户为了一个封面，又是搜图，又是打开电脑用下载姬，折腾半天。

**Comment by coolight7** [comment]
* ok，我们试试用简单的操作实现这个，或者会用别的功能来代替实现这个。

**Comment by coolight7** [comment]
* 已更新该功能，请在官网更新最新版使用
https://download.music.mimicry.cool/
