### ISSUE TITLE
web版本在哪里使用

### ISSUE THREAD

**Issue by RainMz** [coolight7/MimicryMusic#63]
可以自建还是提供web页面使用（类似网易云网页版）

**Comment by RainMz** [comment]
![Screenshot_2024-07-24-03-39-38-063_com mimicry mymusic](https://github.com/user-attachments/assets/65a6f330-2b1c-4a20-97fc-642951a17bc7)
选择其他排序方式后，歌单不会变化，并且在点开排序还是现在用歌曲名排序

**Comment by RainMz** [comment]
![Screenshot_2024-07-24-03-39-32-330_com mimicry mymusic](https://github.com/user-attachments/assets/ee39ae93-206b-4bfc-a05d-2aa37b171771)
![Screenshot_2024-07-24-03-43-48-181_com mimicry mymusic](https://github.com/user-attachments/assets/ee0a0a27-c58b-4444-8cb1-185121dd9c89)

现在的排序是和扫描出的本地音乐排序一致的

**Comment by coolight7** [comment]
web端已经弃用了，现在只有客户端
