### ISSUE TITLE
下载歌曲会把内嵌歌词和歌曲文件分开来

### ISSUE THREAD

**Issue by RainMz** [coolight7/MimicryMusic#67]
webdav中的文件是歌词内嵌到歌曲文件中的，下载后被分开两个文件了
![QQ_1721830501581](https://github.com/user-attachments/assets/0dfba7bb-45c2-4256-b757-3124ed5eb62a)

**Comment by coolight7** [comment]
这个应该没事，歌曲的内嵌歌词仍然是保留的
