### ISSUE TITLE
请问有开发鸿蒙端的计划吗？

### ISSUE THREAD

**Issue by a-kkiri** [coolight7/MimicryMusic#75]
OpenHarmony 平台有对 Flutter SDK 的兼容拓展，请问作者后续有开发鸿蒙端拟声的计划吗？

https://gitee.com/openharmony-sig/flutter_flutter

**Comment by coolight7** [comment]
你好，
- 的确有计划，但需要等其本身的稳定和对常用的依赖库的适配足够
