### ISSUE TITLE
请增加听书倍速功能

### ISSUE THREAD

**Issue by bearduncle520** [coolight7/MimicryMusic#76]
终于找到一个好看的可以播放本地的播放器了。跳过头尾有了，定时关闭有了（建议调整到播放界面更多列表）。就差倍速功能了，建议增加，可以微调到0.5倍速，平时是1.75倍速。感谢

**Comment by coolight7** [comment]
你好，
- 在播放页面左滑两次即可看到播放速度调整
- 另外，安装自动任务插件后，可以对指定歌单或歌曲自动在播放时自动调整速度
