### ISSUE TITLE
Windows版的几条建议

### ISSUE THREAD

**Issue by RuHeShiHaoX** [coolight7/MimicryMusic#86]
1.设置界面藏得太深了，建议在主页面上加个按钮之类的，现在的操作有点繁琐，不符合一般的操作逻辑
![PixPin_2024-10-19_12-55-58](https://github.com/user-attachments/assets/623ed7c7-8ab2-47f9-95a3-d0799535646a)
2.歌曲界面建议做个列表的方式，现在都是大图标，不好看歌曲信息，也不好通过下滑找到对应歌曲，一页显示的信息太少了
![PixPin_2024-10-19_12-57-32](https://github.com/user-attachments/assets/0553f849-1d35-4d9b-80fe-edad55643c68)
3.歌词有点大了，而且没法自定义，建议增加自定义功能，如对齐，字体，颜色，调节大小等
总的来说不错，毕竟才刚开始做，看着还挺正式的，官网什么的一应俱全

**Comment by coolight7** [comment]
- 设置应该放比较少用的东西，所以进入位置隐藏到侧边栏里
- 列表布局在设置-界面-列表布局里调整
- 歌词自定义也在设置-歌词-滚动歌词样式
